import { CloudRain, Droplets, Eye, Wind } from 'lucide-react'
import StatusPill from './StatusPill'
export default function WeatherCard({ points = [], loading, error }) {
  const important = points.reduce((best, point) => !best || ['HIGH_RISK', 'WARNING', 'CAUTION'].indexOf(point.severity) < ['HIGH_RISK', 'WARNING', 'CAUTION'].indexOf(best.severity) ? point : best, null)
  if (loading) return <section className="panel weather-card"><div className="eyebrow">CONDITIONS ALONG ROUTE</div><h2>Weather snapshot</h2><p className="muted">Checking live weather along your route…</p></section>
  if (error || !important) return <section className="panel weather-card"><div className="eyebrow">CONDITIONS ALONG ROUTE</div><h2>Weather snapshot</h2><p className="muted">{error || 'Weather data temporarily unavailable'}</p></section>
  const severity = important.severity.replace('_', ' ')
  return <section className="panel weather-card"><div className="panel-heading"><div><div className="eyebrow">CONDITIONS ALONG ROUTE</div><h2>Weather snapshot</h2></div><span className="data-label">LIVE DATA</span></div><div className="weather-main"><div className="weather-icon"><CloudRain size={32} /></div><div><strong>{important.condition}</strong><span>{important.locationName} · Updated now</span></div><b className="temperature">{Math.round(important.temperature)}°</b></div><div className="weather-stats"><span><Droplets /> <b>{important.rainProbability}%</b> Rain probability</span><span><Wind /> <b>{Math.round(important.windSpeed)} km/h</b> Wind</span><span><Eye /> <b>{important.visibility == null ? '—' : `${important.visibility.toFixed(1)} km`}</b> Visibility</span></div><div className="alert-strip"><CloudRain size={17} /><span><b>{severity === 'NORMAL' ? 'Route weather' : 'Weather alert'}</b> {important.condition} near {important.locationName}.</span><StatusPill level={important.severity === 'NORMAL' ? 'LOW' : important.severity === 'CAUTION' ? 'MEDIUM' : 'HIGH'}>{severity}</StatusPill></div><div className="route-conditions"><b>Route conditions</b>{points.map((point) => <span key={`${point.lat}-${point.lng}`}><i className={point.severity === 'NORMAL' ? 'ok' : 'warn'} /> {point.locationName} — {point.condition} — {Math.round(point.temperature)}°</span>)}</div></section>
}
